schema: ./graphql/schema.graphql
documents: ./graphql/**/*.graphql
extensions:
  codegen:
    generates:
      ./generated-backend.ts:
        plugins:
          - typescript
          - typescript-resolvers
