services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '../..:/workspaces/cached'
        command: sleep infinity
        depends_on:
            - db
    db:
        image: 'mysql:8.0'
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: 'dnd'
        ports:
            - '3306:3306'
